out_dir = "./out"

[treesearch]
num_draft_nodes = 3
debug_prob = 0.3
epsilon = 0.2
max_iterations = 20

[exec]
timeout = 5400

[agent]
k_fold_validation = 1

[agent.code]
model = "gpt-5.2"
model_temp = 1.0