# -*- coding: utf-8 -*-
"""Generate the per-run overview table (Table 1) from scripts/run_status.csv.

Writing the table from the same CSV that feeds the outcome figures means a
change to a status definition propagates to text, table and figures together.
Output: tables/table_runs.tex, included by main.tex.
"""
import csv
from pathlib import Path

HERE = Path(__file__).resolve().parent
OUT = HERE.parent / "tables"
OUT.mkdir(exist_ok=True)

MARK = {True: r"\yes", False: r"--"}
EXTRACTION = {"correct": r"\yes", "incorrect": r"\no",
              "not audited": r"--"}
SCIENTIFIC = {"usable": r"\yes", "partially usable": r"(\yes)",
              "not usable": r"--"}
ARM_LABEL = {
    "L": r"\texttt{gpt-5.4}",
    "M": r"\texttt{gpt-5.4-mini}",
    "T": r"\texttt{deepseek-v4-flash}",
    "C": r"cross-model (\texttt{gpt-5.3-codex} Coder $+$ \texttt{gpt-5.4})",
}


def fmt_cost(row):
    return "---" if float(row["cost_usd"]) == 0 else f"{float(row['cost_usd']):.2f}"


def main():
    rows = list(csv.DictReader((HERE / "run_status.csv").open()))
    lines = [
        r"% Generated by scripts/make_table1.py -- do not edit by hand.",
        r"\begin{tabular}{l r r r r c c c c r c c l}",
        r"\toprule",
        r"\textbf{Run} & \textbf{Time} & \textbf{Cost} & \textbf{Tok.} & "
        r"\textbf{Best} & \textbf{TS} & \textbf{E} & \textbf{S} & "
        r"\textbf{DS} & \textbf{Cond.} & \textbf{X} & \textbf{U} & "
        r"\textbf{Decisive failure} \\",
        r" & (min) & (\$) & (M) & score & & & & (/3) & (/45) & & & \\",
        r"\midrule",
    ]
    for arm in "LMTC":
        arm_rows = [r for r in rows if r["arm"] == arm]
        lines.append(r"\multicolumn{13}{l}{\emph{%s}} \\" % ARM_LABEL[arm])
        for r in arm_rows:
            lines.append(
                "{run} & {t} & {c} & {tok:.1f} & {s:.2f} & {ts} & {e} & {st} & "
                "{ds} & {n} & {x} & {u} & {f} \\\\".format(
                    run=r["run"], t=r["wall_clock_min"], c=fmt_cost(r),
                    tok=int(r["tokens"]) / 1e6, s=float(r["best_reviewer_score"]),
                    ts=MARK[r["tree_search_completed"] == "True"],
                    e=MARK[r["evaluation_output"] == "True"],
                    st=MARK[r["statistical_summary"] == "True"],
                    ds=r["datasets_evaluated"], n=r["conditions_completed"],
                    x=EXTRACTION[r["extraction_verdict"]],
                    u=SCIENTIFIC[r["scientific_status"]],
                    f=r["primary_failure"] or "---"))
        lines.append(r"\midrule" if arm != "C" else "")
    n = len(rows)
    lines += [
        r"\midrule",
        r"\textbf{Total} & & & & & %d & %d & %d & & & %d & %d & \\" % (
            sum(r["tree_search_completed"] == "True" for r in rows),
            sum(r["evaluation_output"] == "True" for r in rows),
            sum(r["statistical_summary"] == "True" for r in rows),
            sum(r["extraction_verdict"] == "correct" for r in rows),
            sum(r["scientific_status"] != "not usable" for r in rows)),
        r"\bottomrule",
        r"\end{tabular}",
    ]
    (OUT / "table_runs.tex").write_text("\n".join(x for x in lines if x) + "\n")
    print(f"wrote {OUT / 'table_runs.tex'} ({n} runs)")


if __name__ == "__main__":
    main()
